services:
  shabadverse:
    build:
      context: .
      args:
        DATA_DIR: ${SHABADVERSE_DATA_BUILD_DIR:-data}
    ports:
      - "127.0.0.1:5050:5050"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
